name: tjclient
description: "A new Flutter TJ_CLIENT project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  http: ^1.2.1
  flutter_paypal_checkout: ^1.0.0
  otp_text_field_v2: ^1.0.3
  dropdown_button2: ^2.3.9
  json_annotation: ^4.8.1
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.2
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  cloud_firestore: ^4.13.6
  intl_phone_field: ^3.2.0
  multi_select_flutter: ^4.1.3
  rename_app: ^1.3.2
  get: ^4.6.6
  flutter:
    sdk: flutter
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  mailer: ^6.1.0
  shared_preferences: ^2.2.3
  jwt_decoder: ^2.0.1
  rolling_bottom_bar: ^0.2.2
  curved_navigation_bar: ^1.0.3
  animated_notch_bottom_bar: ^1.0.3
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.4
  http_auth: ^1.0.4
  webview_flutter: ^4.7.0
  flutter_paypal: ^0.2.0
  provider: ^6.1.2
  animated_splash_screen: ^1.3.0

dependency_overrides:
  http: ^0.13.5


dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/bg.png
    - assets/Picture3.png
    - assets/bracelate.png
    - assets/bracelate.svg
    - assets/necklace.png
    - assets/necklace.svg
    - assets/pendelpng.png
    - assets/ring.png
    - assets/google.png
    - assets/diamongring.png
    - assets/TJlogo.png
